# config/routes.yaml
homepage:
    path: /
    controller: App\Controller\HomeController::index
# config/routes.yaml
client_prenom:
    path: /client/prenom/{prenom}
    controller: App\Controller\ClientController::info
    options: 
        startHour: 15
        endHour: 16
image_home:
    path: /image/home
    controller: App\Controller\ImageController::home
image_affiche:
    path: /data/Images/{reference}
    controller:  App\Controller\ImageController::affiche
