# config/routes.yaml
homepage:
    path: /
    controller: App\Controller\HomeController::index
# config/routes.yaml
client_prenom:
    path: /client/prenom/{prenom}
    controller: App\Controller\ClientController::info
image_home:
    path: /image/home
    controller: App\Controller\ImageController::home